GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/2
###
GET http://localhost:3001/api/persons/666
###
GET http://localhost:3001/api/persons/6081c54cbb1c2bff28c4160b
###
DELETE http://localhost:3001/api/persons/3
###
DELETE http://localhost:3001/api/persons/6081c1363e4d57fd5f7bf4eb
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Bryggare",
    "number": "666-777"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "666-777"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Bryggare"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "666-777"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Bat Man",
    "number": "0700-123123"
}
###
PUT http://localhost:3001/api/persons/6081c54cbb1c2bff28c4160b
Content-Type: application/json

{
    "name": "Bat Man",
    "number": "1337"
}
###
PUT http://localhost:3001/api/persons/6081c54cbb1c2bff28c4160b
Content-Type: application/json

{
    "name": "Bat Man",
    "number": "123456789"
}