GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/2
###
GET http://localhost:3001/api/persons/666
###
GET http://localhost:3001/api/persons/60818c07c21e27f1518f69d9
###
DELETE http://localhost:3001/api/persons/3
###
DELETE http://localhost:3001/api/persons/6081b8b3b32383f93c942bbc
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Bryggare",
    "number": "666-777"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "666-777"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Bryggare"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "666-777"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Bat Man",
    "number": "0700-123123"
}